---
# This playbook just needs to be run once. It configures users for your new server
# as root. Root login is then disabled.
# After that it will run the main software installation playbook as the 'deploy' user

- hosts: all
  user: root
  gather_facts: False
  vars_files:
    - vars/vars.yml

  roles:
    - users

- include: keybits.yml