---
# This playbook just needs to be run once. It configures users for your new server
# After that it will run the main software installation playbook as the deploy users

- hosts: all
  user: root
  gather_facts: False
  vars_files:
    - vars/defaults.yml
    - vars/user.yml

  roles:
    - users

- include: keybits.yml