---
# Set up Ghost for a blog running via Docker

- name: Create nginx virtual host
  template: src=nginx_blog.conf dest=/etc/nginx/sites-available/blog.conf

- name: enable the ghost site
  file: src=/etc/nginx/sites-available/blog.conf dest=/etc/nginx/sites-enabled/blog.conf state=link
  notify: restart nginx

- name: Ensure directory for Ghost user content
  file: dest=/mnt/ghost state=directory

- name: Copy customised config.js to server
  template: src=ghost_config.js dest=/home/deploy/docker-ghost/conf/config.js

- name: Copy Ghost content if this is the first install
  command: cp -r /home/deploy/docker-ghost/ghost-dist/content/ /mnt/ghost creates=/mnt/ghost/content/data/ghost.db

- name: Ensure keybits-casper theme directory
  file: dest=/mnt/ghost/content/themes/keybits-casper state=directory

- name: Create the keybits-casper theme with piwik code
  shell: cp -r /home/deploy/docker-ghost/ghost-dist/content/themes/casper/* /mnt/ghost/content/themes/keybits-casper/ creates=/mnt/ghost/content/themes/keybits-casper/default.hbs

# TODO find a way to use handlebars and jinja together to allow custom theme file building
#- name: Copy our customised default.hbs
#  copy: src=ghost-default.hbs dest=/mnt/ghost/content/themes/keybits-casper/default.hbs backup=yes

#- name: Copy our js file for piwik
#  template: src=ghost-piwik.js dest=/mnt/ghost/content/themes/keybits-casper/assets/js/ghost-piwik.js

- name: Stop running ghost docker image
  docker: image=keybits-ghost state=stopped

- name: Stop ufw
  command: ufw disable

- name: Build docker-ghost
  command: docker build -t keybits-ghost . chdir=/home/deploy/docker-ghost/

- name: Start ufw
  command: ufw --force enable

- name: Set permissions on host mount of Ghost files to allow editing by main user
  file: path=/mnt/ghost recurse=yes owner={{ main_user_name }} group={{ main_user_name }} state=directory

