---
# Only build Ghost if docker-ghost github repo changed

- name: Get docker-ghost repo from GitHub
  git: repo=https://github.com/Keybits/docker-ghost.git dest=/home/deploy/docker-ghost/
  register: ghrepoupdated

- include: ghost-build.yml
  when: ghrepoupdated.changed == True

# TODO - not reliable at the moment
#- name: Ensure docker-ghost started
#  docker: image=keybits-ghost ports=2368:2368 volumes=/mnt/ghost/content:/srv/ghost/content command=/start state=present

- name: Ensure docker-ghost started
  command: docker run -d -p=2368:2368 -v=/mnt/ghost/content:/srv/ghost/content keybits-ghost /start