---
# Only build Ghost if github repo changed

- name: Get docker-ghost repo from GitHub
  git: repo=https://github.com/Keybits/docker-ghost.git dest=/home/deploy/docker-ghost/
  register: repoupdated

#- include: ghost-build.yml
#  when: repoupdated.changed == True