---
# Set up piwik for analytics running via Docker

- name: Get docker-piwik repo from GitHub
  git: repo=https://github.com/Keybits/docker-piwik.git dest=/home/deploy/docker-piwik/
  register: pwrepoupdated

- include: piwik-build.yml
  when: pwrepoupdated.changed == True

