---
# Only build piwik if github repo has changed

- name: Ensure directory for piwik database
  file: dest=/mnt/piwik state=directory

- name: Stop running piwik docker image
  docker: image=keybits/piwik state=stopped

- name: Build docker-piwik
  command: docker build -t keybits/piwik . chdir=/home/deploy/docker-piwik/

- name: Create nginx virtual host
  template: src=nginx_analytics.conf dest=/etc/nginx/sites-available/analytics.conf

- name: enable the analytics site
  file: src=/etc/nginx/sites-available/analytics.conf dest=/etc/nginx/sites-enabled/analytics.conf state=link
  notify: restart nginx