---
# Set up piwik for analytics running via Docker

- name: Ensure directory for piwik database
  file: dest=/mnt/piwik state=directory

- name: Get docker-piwik repo from GitHub
  git: repo=https://github.com/Keybits/docker-piwik.git dest=/home/deploy/docker-piwik/

- name: Build docker-piwik
  command: docker build -t keybits/piwik . chdir=/home/deploy/docker-piwik/

- name: Run docker-piwik
  docker: image=keybits/piwik command=/start ports=10000:80 volumes=/mnt/piwik:/data

# now get piwik db-password for setting up piwik
# TODO: ideal would be to set up the first piwik site via Ansible

# TODO: get ansible to set this password and display it here
- name: Display Piwik db password info
  debug: msg="The password for the piwik atabase is in /mnt/piwik/ on your server. Go to ttp://analytics.{{ domain }} to set up piwik. Docs are at http://docs.keybits.net"

- name: Create nginx virtual host
  template: src=nginx_analytics.conf dest=/etc/nginx/sites-available/analytics.conf

- name: enable the analytics site
  file: src=/etc/nginx/sites-available/analytics.conf dest=/etc/nginx/sites-enabled/analytics.conf state=link
  notify: restart nginx
